### ISSUE TITLE
Overwriting pixels

### ISSUE THREAD

**Issue by vedadayananda** [RENCI/Segmentor#118]
Removing the "done" status from a finished nucleus if its pixels are overwritten

**Comment by davidborland** [comment]
I think the other option here would be to not allow pixels from a finished nucleus to be overwritten, forcing the user to remove the done status manually before doing so. This would probably be more consistent behavior (not allowing done regions to be edited at all).

What do you think @JustKeepClimbing ?

**Comment by JustKeepClimbing** [comment]
hi @davidborland , I agree with your suggestion (manually have tracer remove the 'done' status). @vedadayananda suggested this because our presently agreed upon tracing technique is to 'smooth out' the surface of the nuclei. This sometimes is not apparent when two nuclei are sharing pixel boundaries. For now, I think this issue can be addressed by either A) preventing tracers from overwriting 'done' pixels or B) having a message pop up that says something like, "Would you like to overwrite 'done' pixels? If so, the 'done' status for this nucleus will be removed." .. with 'Yes' or 'No' options so that the tracer is still making the decision.

**Comment by davidborland** [comment]
Implemented option A. We can revisit if we want to try option B instead.
